#pragma once
#include <stdint.h>
#include <vector>
#include <intrin.h>

class Sarah
{
public:
	class Offsets
	{
	public:
		static inline uint64_t ImageBase;
		static inline uint64_t GWorld;
		static inline uint64_t GEngine;
		static inline uint64_t GUObjectArray;
		static inline uint64_t GUObjectArrayNum;
		static inline uint64_t GIsClientFalse;
		static inline uint64_t GIsClientTrue;
		static inline uint64_t IFaceForBC;
		static inline uint64_t IFaceForPC;
		static inline uint64_t Step;
		static inline uint64_t StepExplicitProperty;
		static inline uint64_t FNameCtor;
		static inline uint64_t AppendString;
		static inline uint64_t StaticFindObject;
		static inline uint64_t StaticLoadObject;
		static inline uint64_t GetInterfaceAddress;
		static inline uint64_t SpawnActorTransform;
		static inline uint64_t SpawnActorLocRot;
		static inline uint64_t FinishSpawning;
		static inline uint64_t AddTag;
		static inline uint64_t GetSparseClassData;
		static inline uint64_t Realloc;
		static inline uint64_t FWeakObjectPtrGet;
		static inline uint64_t LoadSynchronous;
		static inline uint64_t CreateNetDriver;
		static inline uint64_t InitListen;
		static inline uint64_t SetWorld;
		static inline uint64_t GetWorldContext;
		static inline uint64_t TickFlush;
		static inline uint64_t GetMaxTickRate;
		static inline uint64_t DispatchRequest;
		static inline uint64_t WorldNetMode;
		static inline uint64_t WorldNetMode2;
		static inline uint64_t SendClientAdjustment;
		static inline uint64_t UpdateIrisReplicationViews;
		static inline uint64_t PreSendUpdate;
		static inline uint64_t Listen;
		static inline uint64_t CheckCheckpointHeartBeat;
		static inline uint64_t ServerMovePerformMovement;
		static inline uint64_t RegisterTickFunction;
		static inline uint64_t GetTickableTickType;
		static inline uint64_t WorldNetModePatch;
		static inline uint64_t ReadyToStartMatch;
		static inline uint64_t SpawnDefaultPawnFor;
		static inline uint64_t FinishWorldInitialization;
		static inline uint64_t HandleMatchHasStarted;
		static inline uint64_t HandleMatchHasEnded;
		static inline uint64_t GetGameSessionClass;
		static inline uint64_t PickTeam;
		static inline uint64_t Login;
		static inline uint64_t CountReadyPlayers;
		static inline uint64_t AreAllAdditionalPlaylistLevelsVisible;
		static inline uint64_t GetFeatureDataIfActive;
		static inline uint64_t SetupSafeZonePhase;
		static inline uint64_t SpawnSupplyDrop;
		static inline uint64_t NotifyGameMemberAdded;
		static inline uint64_t NotifyDeath;
		static inline uint64_t OnPawnDied;
		static inline uint64_t ApplyCharacterCustomization;
		static inline uint64_t InitializePlayerGameplayAbilities;
		static inline uint64_t CanAffordToPlaceBuildableClass;
		static inline uint64_t ServerCreateBuildingActor;
		static inline uint64_t PayBuildableClassPlacementCost;
		static inline uint64_t CanBePlayerEdited;
		static inline uint64_t SetEditingPlayer;
		static inline uint64_t ReplaceBuildingActor;
		static inline uint64_t CanSpectateActor;
		static inline uint64_t ShouldSuicideOnSpectate;
		static inline uint64_t BeginSpectating;
		static inline uint64_t SetViewTargetAndNotifyClient;
		static inline uint64_t SetCosmeticLoadoutController;
		static inline uint64_t GetPlayerViewPoint;
		static inline uint64_t ControllerReset;
		static inline uint64_t InternalTryActivateAbility;
		static inline uint64_t ClearAbility;
		static inline uint64_t GiveAbilityAndActivateOnce;
		static inline uint64_t ConstructAbilitySpec;
		static inline uint64_t SetToDirtyInternal;
		static inline uint64_t SpawnPickup;
		static inline uint64_t GetItemInternal;
		static inline uint64_t GetReplicatedItemEntryInternal;
		static inline uint64_t GetTraits;
		static inline uint64_t GetPickupComponent;
		static inline uint64_t GetSlotSize;
		static inline uint64_t TryToAutoPickup;
		static inline uint64_t GetLevelLimits;
		static inline uint64_t GetLevelMapping;
		static inline uint64_t OnAuthorityRandomUpgradeApplied;
		static inline uint64_t SpawnLoot;
		static inline uint64_t SetPickupTarget;
		static inline uint64_t GetDepositGoal;
		static inline uint64_t GetAutoCreateAttachmentBuildingShapes;
		static inline uint64_t GetBuildingTypeFromBuildingAttachmentType;
		static inline uint64_t CreateBuildingAndSpawnDeco;
		static inline uint64_t ExternalShouldDropOrDestroyByItemType;
		static inline uint64_t GetRow;
		static inline uint64_t DropLootOnDeath;
		static inline uint64_t InitializeSkills;
		static inline uint64_t PossessPawn;
		static inline uint64_t CosmeticLoadoutOnSpawned;
		static inline uint64_t WouldItemFitInBotInventory;
		static inline uint64_t FindWeaponTypeForStats;
		static inline uint64_t SetBotInventoryItem;
		static inline uint64_t ForceForgetEnemy;
		static inline uint64_t PerceptionCompTickComponent;
		static inline uint64_t RegisterToLivingWorldManager;
		static inline uint64_t CreateAndConfigureNavigationSystem;
		static inline uint64_t HandleZiplineStateChanged;
		static inline uint64_t ForceLaunchPlayerZiplining;
		static inline uint64_t UpdateDBNOInteractCollision;
		static inline uint64_t OnPawnRevived;
		static inline uint64_t OnDBNOHoisterChanged;
		static inline uint64_t EquipWeapon;
		static inline uint64_t EquipVehicleWeapon;
		static inline uint64_t OnUnEquip;
		static inline uint64_t ConstructRuntimeCtx;
		static inline uint64_t OnExtensionPush;
		static inline uint64_t OnExtensionDeactivate;
		static inline uint64_t GetExtObj;
		static inline uint64_t GetVehicleModConfigFromTag;
		static inline uint64_t ApplyToVehicleInternal;
		static inline uint64_t SetIsDoorOpen;
		static inline uint64_t ServerOnAttemptInteract;
		static inline uint64_t OpenActor;
		static inline uint64_t CurlHttpRequestConstructor;
		static inline uint64_t CurlHttpInternalSetURL;
		static inline uint64_t CurlHttpInternalSetVerb;
		static inline uint64_t CurlHttpInternalSetHeader;
		static inline uint64_t CurlHttpInternalSetContent;
		static inline uint64_t CurlHttpInternalSetContentConst;
		static inline uint64_t CurlHttpInternalSetContentAsString;
		static inline uint64_t CurlHttpInternalProcessRequest;
		static inline uint64_t CurlHttpBindRaw;
		static inline uint64_t CurlHttpInternalGetHeader;
		static inline uint64_t CurlHttpInternalGetContent;
		static inline uint64_t CurlHttpInternalGetResponseCode;
		static inline uint64_t CurlHttpInternalGetContentAsString;
		static inline uint64_t CurlHttpInternalCreateRequest;
		static inline uint64_t GetHttpModule;
		static inline uint64_t ActivatePhase;
		static inline uint64_t PatchUnsafeEnvironment;
		static inline uint64_t PatchRequestExit;
		static inline uint64_t PatchChangeGameSessionIDCrash1;
		static inline uint64_t PatchChangeGameSessionIDCrash2;
		static inline uint64_t PatchGFXCrash;
		static inline uint64_t PatchPedestalBeginPlay;
		static inline uint64_t PatchKickPlayer;
		static inline uint64_t PatchSpawnServerActor;
		static inline uint64_t Patch721A50C;
		static inline uint64_t PatchControllerDisconnected;
		static inline uint64_t PatchUpdRequired;
		static inline uint64_t PatchNotherController;
		static inline uint64_t PatchGoofyCrash;
		static inline uint64_t PatchMoreCrash;
		static inline uint64_t PatchPawnCrash;
		static inline uint64_t PatchWepCrash;
		static inline uint64_t PatchWidgetCrash1;
		static inline uint64_t PatchWidgetCrash2;
		static inline uint64_t PatchGamephaseStep;
		static inline uint64_t PatchRespawnKick;
		static inline uint64_t PatchLocalPlayerSpawnPlayActor;
		static inline uint64_t PatchLocalPlayerSpawnPlayActorRet;
		static inline uint64_t PatchEntitlementCrash;
		static inline uint64_t PatchCanActivateAbility;
		static inline uint64_t PatchCanActivateAbilityRet;
		static inline uint64_t PatchCosmeticCrash;
		static inline uint64_t PatchFireSpreadFix;
		static inline uint64_t PatchCollectorActor;
		static inline uint64_t PatchCollectorActor2;
		static inline uint64_t PatchCosmeticLoadout;
		static inline uint32_t ServerAcknowledgePossessionVft;
		static inline uint32_t HandleStartingNewPlayerVft;
		static inline uint32_t ServerExecuteInventoryItemVft;
		static inline uint32_t ServerAttemptAircraftJumpVft;
		static inline uint32_t InternalServerTryActivateAbilityVft;
		static inline uint32_t GrantOutputVft;
		static inline uint32_t AttemptSpawnResourcesVft;
		static inline uint32_t AIBotSkillsetOnSpawnedVft;
		static inline uint32_t SetLoadedAmmoVft;
		static inline uint32_t SetPhantomReserveAmmoVft;
		static inline uint32_t SpawnDecoInternalVft;
		static inline uint32_t CreateBuildingAndSpawnDecoInternalVft;
		static inline uint32_t ShouldAllowServerSpawnDecoVft;
		static inline uint32_t SpawnDecoVft;
		static inline uint32_t GivePickupToVft;
		static inline uint32_t ServerCreateBuildingActorVft;
		static inline uint32_t ServerBeginEditingBuildingActorVft;
		static inline uint32_t ServerEditBuildingActorVft;
		static inline uint32_t ServerEndEditingBuildingActorVft;
		static inline uint32_t ServerRestartPlayerVft;
		static inline uint32_t ServerOnMaterialSelectionVft;
		static inline uint32_t ServerAttemptInventoryDropVft;
		static inline uint32_t ServerPlayEmoteItemVft;
		static inline uint32_t DropItemsOnPawnDestructionVft;
		static inline uint32_t ServerSpectateActorVft;
		static inline uint32_t ServerSuicideVft;
		static inline uint32_t ServerSetMultiProductCosmeticLoadoutVft;
		static inline uint32_t ServerCheatVft;
		static inline uint32_t ServerReturnToMainMenuVft;
		static inline uint32_t ForceEquipValidWeaponVft;
		static inline uint32_t ServerHandlePickupInfoVft;
		static inline uint32_t ServerSendZiplineStateVft;
		static inline uint32_t ServerHoistDBNOPlayerVft;
		static inline uint32_t ServerInterrogateDBNOPlayerVft;
		static inline uint32_t ServerThrowCarriedPlayerVft;
		static inline uint32_t NeedsLoadForClientVft;

		static inline std::vector<uint64_t> NullFuncs;
		static inline std::vector<uint64_t> RetTrueFuncs;

		static int Init()
		{
			ImageBase = *(uint64_t*)(__readgsqword(0x60) + 0x10);

			GWorld = ImageBase + 0x12ED8E38;
			GEngine = ImageBase + 0x12D6E978;
			GUObjectArray = ImageBase + 0x12EAF270;
			GUObjectArrayNum = ImageBase + 0x12EAF284;
			GIsClientFalse = ImageBase + 0x12D4E1CA;
			GIsClientTrue = ImageBase + 0x12D4E166;
			IFaceForBC = ImageBase + 0xFB3F4B8;
			IFaceForPC = ImageBase + 0xF85B548;
			Step = ImageBase + 0x160F4E4;
			StepExplicitProperty = ImageBase + 0x1B5C108;
			FNameCtor = ImageBase + 0x175DD98;
			AppendString = ImageBase + 0x175D6E0;
			StaticFindObject = ImageBase + 0x1A2CAB8;
			StaticLoadObject = ImageBase + 0x1CB5254;
			GetInterfaceAddress = ImageBase + 0x16574E4;
			SpawnActorTransform = ImageBase + 0x1B54FA8;
			SpawnActorLocRot = ImageBase + 0x2FA7A58;
			FinishSpawning = ImageBase + 0x21F5F6C;
			AddTag = ImageBase + 0x1895690;
			GetSparseClassData = ImageBase + 0x1BBBDC8;
			Realloc = ImageBase + 0x521CFCC;
			FWeakObjectPtrGet = ImageBase + 0x4B6D02C;
			LoadSynchronous = ImageBase + 0x15685E4;
			CreateNetDriver = ImageBase + 0x2EF3758;
			InitListen = ImageBase + 0x734AB88;
			SetWorld = ImageBase + 0x29664C8;
			GetWorldContext = ImageBase + 0x1973A84;
			TickFlush = ImageBase + 0x23CE5C4;
			GetMaxTickRate = ImageBase + 0x189FE98;
			DispatchRequest = ImageBase + 0x7DE4ED0;
			WorldNetMode = ImageBase + 0x16562A4;
			WorldNetMode2 = ImageBase + 0x2196B08;
			SendClientAdjustment = ImageBase + 0x71152EC;
			UpdateIrisReplicationViews = ImageBase + 0x705EBE4;
			PreSendUpdate = ImageBase + 0x63BF4A4;
			Listen = ImageBase + 0x2C283E0;
			CheckCheckpointHeartBeat = ImageBase + 0x521AFC0;
			ServerMovePerformMovement = ImageBase + 0x9E5754C;
			RegisterTickFunction = ImageBase + 0x19F7AFC;
			GetTickableTickType = ImageBase + 0x4139B6C;
			WorldNetModePatch = ImageBase + 0x219827C;
			ReadyToStartMatch = ImageBase + 0x918B180;
			SpawnDefaultPawnFor = ImageBase + 0x918E5B8;
			FinishWorldInitialization = ImageBase + 0x918177C;
			HandleMatchHasStarted = ImageBase + 0x9184E1C;
			HandleMatchHasEnded = ImageBase + 0x9184AC0;
			GetGameSessionClass = ImageBase + 0x3F46314;
			PickTeam = ImageBase + 0x9189894;
			Login = ImageBase + 0x9186E98;
			CountReadyPlayers = ImageBase + 0x917E138;
			AreAllAdditionalPlaylistLevelsVisible = ImageBase + 0x9A52B40;
			GetFeatureDataIfActive = ImageBase + 0x1862848;
			SetupSafeZonePhase = ImageBase + 0x9101F80;
			SpawnSupplyDrop = ImageBase + 0x910A478;
			NotifyGameMemberAdded = ImageBase + 0x27E12C0;
			NotifyDeath = ImageBase + 0x918B8D4;
			OnPawnDied = ImageBase + 0x921754C;
			ApplyCharacterCustomization = ImageBase + 0xA2C731C;
			InitializePlayerGameplayAbilities = ImageBase + 0x9A8894C;
			CanAffordToPlaceBuildableClass = ImageBase + 0xA21CED8;
			ServerCreateBuildingActor = ImageBase + 0x91F7F14;
			PayBuildableClassPlacementCost = ImageBase + 0xA24BD50;
			CanBePlayerEdited = ImageBase + 0x952C704;
			SetEditingPlayer = ImageBase + 0x9539A08;
			ReplaceBuildingActor = ImageBase + 0x9538A78;
			CanSpectateActor = ImageBase + 0x91F920C;
			ShouldSuicideOnSpectate = ImageBase + 0x922D66C;
			BeginSpectating = ImageBase + 0xA2C9730;
			SetViewTargetAndNotifyClient = ImageBase + 0x9229B74;
			SetCosmeticLoadoutController = ImageBase + 0x9672F80;
			GetPlayerViewPoint = ImageBase + 0x1C9AC68;
			ControllerReset = ImageBase + 0x7113FD8;
			InternalTryActivateAbility = ImageBase + 0x7CBB438;
			ClearAbility = ImageBase + 0x7CA8DBC;
			GiveAbilityAndActivateOnce = ImageBase + 0x7CBA17C;
			ConstructAbilitySpec = ImageBase + 0x7CF6F98;
			SetToDirtyInternal = ImageBase + 0x9CA8768;
			SpawnPickup = ImageBase + 0x9CDB314;
			GetItemInternal = ImageBase + 0x2B4A6E4;
			GetReplicatedItemEntryInternal = ImageBase + 0x2B4A76C;
			GetTraits = ImageBase + 0x21FB6AC;
			GetPickupComponent = ImageBase + 0x1BC59A8;
			GetSlotSize = ImageBase + 0x8338174;
			TryToAutoPickup = ImageBase + 0xA1A5418;
			GetLevelLimits = ImageBase + 0x3B44AE8;
			GetLevelMapping = ImageBase + 0x9CE5EEC;
			OnAuthorityRandomUpgradeApplied = ImageBase + 0x94C7DCC;
			SpawnLoot = ImageBase + 0x94CCD48;
			SetPickupTarget = ImageBase + 0x9CDB4C8;
			GetDepositGoal = ImageBase + 0x34AA988;
			GetAutoCreateAttachmentBuildingShapes = ImageBase + 0x9C9B350;
			GetBuildingTypeFromBuildingAttachmentType = ImageBase + 0xA679798;
			CreateBuildingAndSpawnDeco = ImageBase + 0xA22B5C8;
			ExternalShouldDropOrDestroyByItemType = ImageBase + 0x9206ADC;
			GetRow = ImageBase + 0xA76BC00;
			DropLootOnDeath = ImageBase + 0xA778F28;
			InitializeSkills = ImageBase + 0xA789FB0;
			PossessPawn = ImageBase + 0xA2C86CC;
			CosmeticLoadoutOnSpawned = ImageBase + 0xA8A7A34;
			WouldItemFitInBotInventory = ImageBase + 0xA7A1DE8;
			FindWeaponTypeForStats = ImageBase + 0x356C5A4;
			SetBotInventoryItem = ImageBase + 0xA7980C0;
			ForceForgetEnemy = ImageBase + 0xA77C940;
			PerceptionCompTickComponent = ImageBase + 0x9B436C8;
			RegisterToLivingWorldManager = ImageBase + 0xB4E282C;
			CreateAndConfigureNavigationSystem = ImageBase + 0xA7EAB6C;
			HandleZiplineStateChanged = ImageBase + 0xA190360;
			ForceLaunchPlayerZiplining = ImageBase + 0xA18612C;
			UpdateDBNOInteractCollision = ImageBase + 0x3215E94;
			OnPawnRevived = ImageBase + 0xA2A1D70;
			OnDBNOHoisterChanged = ImageBase + 0x37B8694;
			EquipWeapon = ImageBase + 0xA145620;
			EquipVehicleWeapon = ImageBase + 0xA610714;
			OnUnEquip = ImageBase + 0xA68A44C;
			ConstructRuntimeCtx = ImageBase + 0x1BCE080;
			OnExtensionPush = ImageBase + 0x351D4B8;
			OnExtensionDeactivate = ImageBase + 0x2DD1638;
			GetExtObj = ImageBase + 0x2DD10D4;
			GetVehicleModConfigFromTag = ImageBase + 0x9BCADB8;
			ApplyToVehicleInternal = ImageBase + 0xA60996C;
			SetIsDoorOpen = ImageBase + 0x955C49C;
			ServerOnAttemptInteract = ImageBase + 0x94F0474;
			OpenActor = ImageBase + 0x8E47384;
			CurlHttpRequestConstructor = ImageBase + 0x2072D54;
			CurlHttpInternalSetURL = ImageBase + 0x2768148;
			CurlHttpInternalSetVerb = ImageBase + 0x2768090;
			CurlHttpInternalSetHeader = ImageBase + 0x2769FA4;
			CurlHttpInternalSetContent = ImageBase + 0x3C4332C;
			CurlHttpInternalSetContentConst = ImageBase + 0x5F906B8;
			CurlHttpInternalSetContentAsString = ImageBase + 0x3C431D8;
			CurlHttpInternalProcessRequest = ImageBase + 0x2C0DC40;
			CurlHttpBindRaw = ImageBase + 0x6C4CEC0;
			CurlHttpInternalGetHeader = ImageBase + 0x3227FA8;
			CurlHttpInternalGetContent = ImageBase + 0x206D064;
			CurlHttpInternalGetResponseCode = ImageBase + 0x4B3D250;
			CurlHttpInternalGetContentAsString = ImageBase + 0x35E5EA4;
			CurlHttpInternalCreateRequest = ImageBase + 0x20737F4;
			GetHttpModule = ImageBase + 0x1E5F354;
			ActivatePhase = ImageBase + 0xC2AA930;
			PatchUnsafeEnvironment = ImageBase + 0x537F4A0;
			PatchRequestExit = ImageBase + 0x4336BAC;
			PatchChangeGameSessionIDCrash1 = ImageBase + 0x27B3958;
			PatchChangeGameSessionIDCrash2 = ImageBase + 0x27B3598;
			PatchGFXCrash = ImageBase + 0x1D91EEC;
			PatchPedestalBeginPlay = ImageBase + 0x2C7D6F0;
			PatchKickPlayer = ImageBase + 0x1BED9A8;
			PatchSpawnServerActor = ImageBase + 0x338C8F8;
			Patch721A50C = ImageBase + 0x721A50C;
			PatchControllerDisconnected = ImageBase + 0x2C7736C;
			PatchUpdRequired = ImageBase + 0x3E2C464;
			PatchNotherController = ImageBase + 0x2C78CDC;
			PatchGoofyCrash = ImageBase + 0x3E6E09D;
			PatchMoreCrash = ImageBase + 0x27306AC;
			PatchPawnCrash = ImageBase + 0xAF29848;
			PatchWepCrash = ImageBase + 0x19D7D70;
			PatchWidgetCrash1 = ImageBase + 0x2CAF22C;
			PatchWidgetCrash2 = ImageBase + 0x2CB06C8;
			PatchGamephaseStep = ImageBase + 0x1E349CB;
			PatchRespawnKick = ImageBase + 0xA6E634D;
			PatchLocalPlayerSpawnPlayActor = ImageBase + 0x20AEF8C;
			PatchLocalPlayerSpawnPlayActorRet = ImageBase + 0x20AEF90;
			PatchEntitlementCrash = ImageBase + 0x9B2A080;
			PatchCanActivateAbility = ImageBase + 0x7C86D88;
			PatchCanActivateAbilityRet = ImageBase + 0x7C86D8C;
			PatchCosmeticCrash = ImageBase + 0x6D3E210;
			PatchFireSpreadFix = ImageBase + 0xC6A3B28;
			PatchCollectorActor = ImageBase + 0x950A242;
			PatchCollectorActor2 = ImageBase + 0x950A246;
			PatchCosmeticLoadout = ImageBase + 0x96774B4;
			ServerAcknowledgePossessionVft = 0x135;
			HandleStartingNewPlayerVft = 0xEE;
			ServerExecuteInventoryItemVft = 0x232;
			ServerAttemptAircraftJumpVft = 0xAA;
			InternalServerTryActivateAbilityVft = 0x11D;
			GrantOutputVft = 0x194;
			AttemptSpawnResourcesVft = 0x1A5;
			AIBotSkillsetOnSpawnedVft = 0x5B;
			SetLoadedAmmoVft = 0xC4;
			SetPhantomReserveAmmoVft = 0xC5;
			SpawnDecoInternalVft = 0x19B;
			CreateBuildingAndSpawnDecoInternalVft = 0x19D;
			ShouldAllowServerSpawnDecoVft = 0x1A3;
			SpawnDecoVft = 0x198;
			GivePickupToVft = 0xEB;
			ServerCreateBuildingActorVft = 0x253;
			ServerBeginEditingBuildingActorVft = 0x25A;
			ServerEditBuildingActorVft = 0x255;
			ServerEndEditingBuildingActorVft = 0x258;
			ServerRestartPlayerVft = 0x12D;
			ServerOnMaterialSelectionVft = 0x247;
			ServerAttemptInventoryDropVft = 0x23D;
			ServerPlayEmoteItemVft = 0x1FD;
			DropItemsOnPawnDestructionVft = 0x39F;
			ServerSpectateActorVft = 0x48C;
			ServerSuicideVft = 0x28C;
			ServerSetMultiProductCosmeticLoadoutVft = 0x4CE;
			ServerCheatVft = 0x1FB;
			ServerReturnToMainMenuVft = 0x283;
			ForceEquipValidWeaponVft = 0x2F6;
			ServerHandlePickupInfoVft = 0x252;
			ServerSendZiplineStateVft = 0x261;
			ServerHoistDBNOPlayerVft = 0x23E;
			ServerInterrogateDBNOPlayerVft = 0x23D;
			ServerThrowCarriedPlayerVft = 0x23C;
			NeedsLoadForClientVft = 0x36;

			NullFuncs.clear();
			RetTrueFuncs.clear();

			return 0;
		}
	};
};
